#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("arkecho_app.source.Resource", IsApplication=true)]

namespace arkecho_app.source
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::arkecho_app.source.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::arkecho_app.source.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::arkecho_app.source.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int cActionBarBackground = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int cActionBarTextColor = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int cMainBackground = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int cMainTextColor = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int defaultMusicIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int menuIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int playerIcon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080010
			public const int ButtonLayout = 2131230736;
			
			// aapt resource value: 0x7f080015
			public const int contentFrame = 2131230741;
			
			// aapt resource value: 0x7f080014
			public const int imageView1 = 2131230740;
			
			// aapt resource value: 0x7f08000d
			public const int imageViewCoverArt = 2131230733;
			
			// aapt resource value: 0x7f080001
			public const int pbActionBarBack = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int pbActionBarMenu = 2131230725;
			
			// aapt resource value: 0x7f080011
			public const int pbBackward = 2131230737;
			
			// aapt resource value: 0x7f08000b
			public const int pbConnectManually = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int pbConnectWithQr = 2131230732;
			
			// aapt resource value: 0x7f080013
			public const int pbForward = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int pbPlay_Pause = 2131230738;
			
			// aapt resource value: 0x7f080004
			public const int space1 = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int space2 = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int space3 = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int space4 = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int teAddress = 2131230730;
			
			// aapt resource value: 0x7f080017
			public const int top_menu_help = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int top_menu_impressum = 2131230742;
			
			// aapt resource value: 0x7f080009
			public const int tvAddress = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int tvHeader = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int tvHilfe = 2131230727;
			
			// aapt resource value: 0x7f08000f
			public const int tvInterpretPlayer = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int tvTitlePlayer = 2131230734;
			
			// aapt resource value: 0x7f080003
			public const int twActionBarTitle = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActionBar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Help = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Impressum = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Player = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Splash = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int zxingscanneractivitylayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int zxingscannerfragmentlayout = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int top_menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationTitle = 2131034113;
			
			// aapt resource value: 0x7f050010
			public const int HelpActivityTextViewHeader = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int HelpActivityTitle = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int ImpressumActivityTextViewHeader = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int ImpressumActivityTitle = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int MainActivityPushButtonConnectManual = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int MainActivityPushButtonConnectQr = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int MainActivityTextViewAddress = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int MainActivityTextViewHeader = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int MainActivityTitle = 2131034114;
			
			// aapt resource value: 0x7f050014
			public const int MsgBoxTextConnectionEnded = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int MsgBoxTitleError = 2131034131;
			
			// aapt resource value: 0x7f05000a
			public const int PlayerActivityButtonBackward = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int PlayerActivityButtonForward = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int PlayerActivityButtonPlay_Pause = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int PlayerActivityTextViewInterpretDefault = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int PlayerActivityTextViewTitleDefault = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int PlayerActivityTitle = 2131034119;
			
			// aapt resource value: 0x7f050012
			public const int QrScannerTextBottom = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int QrScannerTextTop = 2131034129;
			
			// aapt resource value: 0x7f050017
			public const int ToastEmptyWrongAddress = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int ToastNoConnection = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int ToastQrScanFailed = 2131034133;
			
			// aapt resource value: 0x7f050019
			public const int TopMenuHelp = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int TopMenuImpressum = 2131034136;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int ArkEcho_ActionBar = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int ArkEcho_Main = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int ArkEcho_SplashScreen = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
