#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("arkecho_app.source.Resource", IsApplication=true)]

namespace arkecho_app.source
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::arkecho_app.source.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::arkecho_app.source.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::arkecho_app.source.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int playerIcon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int ButtonLayout = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int contentFrame = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int imageView1 = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int pbBackward = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int pbConnectManually = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int pbConnectWithQr = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int pbForward = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int pbPlay_Pause = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int teAddress = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int textAdresse = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MainActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PlayerActivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int zxingscanneractivitylayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int zxingscannerfragmentlayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationTitle = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int ButtonBackward = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int ButtonConnectManual = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int ButtonConnectQr = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int ButtonForward = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int ButtonPlay_Pause = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
